/** @file exit.S
 *
 * @brief exit sycall wrapper
 *
 * @author Mike Kasick <mkasick@andrew.cmu.edu>
 * @date   Sun, 07 Oct 2007 01:52:31 -0400
 * 
 * @author Kartik Subramanian <ksubrama@andrew.cmu.edu>
 * @date 2008-10-29
 */
@ exit.S: exit sycall wrapper
@
@ Authors: Brandon Lee <bfl>
@          Christopher Palmer <ctpalmer>
@          Jongyoon Han <jongyoo1>
@          Lawrence Tsang <ltsang>
@
@ Date:    October 7th 2012
@
@ An assembly function that exits.

#include <asm.h>
#include <bits/swi.h>

	.file "exit.S"

FUNC(exit)
	swi	EXIT_SWI
